language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: XCbpo+Sk/cfZFminFHVvXboH6rxqYydpo/kDLm4Cf9llRpUgKmVj+Ov2a62J4LlKbJHlJ24cEBS3F9ZziazEje7Qj3jI3jSzRanwPIKAqwehDfBbNvZjaWsELhZVtBBNdTiJON2wdKPw7r8C9tLPu6jXM4XyPv7vQ31Pg1dgOP48uhVoMA/zPhoCpDIS267OVXj4Us0+GCFt1yhIeWdQZk+LOH2hRDV0PtwnJC5X+5rf5QDzt2sth31msclPE5vL+hK72JEhhyxKAXv4eST+ayZsxbrAXZW9XwHWa5zvf+r6sbvTYAMWdo/SU3GL3OLRZ9mpagUPvo47W3JxO0xC3nrpjzc5YkukQjonCP87mS04HZ2vhEbjmmj/pI/5p3TwisDWJfDtOFUj8VX1dX/vFXPUA++Va5oqaoZ69CkS3+XoGpEYbidoqDEUw0OzYWnE4KMDmF4Bgooeku+OyDpEUCniCdfdVhPkNQ1DnhV2RQiZ6UdK0igkhEgyNyXKamqowb7Pv/fB/bKjaXPTZSKGpUzOb3bM/+aPHROe+dKrYODiiA4n72nK7Y9OysQFuvuPnxj7mB1TaqSNYVan1PkTylZhxsZEOIEwiUpADcY7ajL5IJyjoSkT9+4Jjh6vJcz0uPIlsvUiExtBxTWzWjexjPfk2wYu6mE1yEVG5+ZkILY=
  on:
    tags: true
    repo: PaNOSC-ViNYL/SimEx-Lite
    python: 3.8
