language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: JunCEEE
  password:
    secure: 1az2WMSD+GsP8vvsBb1QrZEcdZKqoNd0mARHl0Dj9g2lg9mdlGBAyzBiyRQ2JCR+9UkTM2UtpO2rsYocMGBzsPjb6ef7EYKK6hfkpNXej4cC9HPYM4BugxKArCvycT1Y4+y5nbf9tv/BBMMmLCeBdMd6mfWHw/RBoxgASVs9zKc+yRWeuBAEr5hQoPxffVI31egqb1gEbUtWkuFFsKoAbx1BspNL2LpHe5ebvFjm2ELBGBDsuGSVBltcL6fdN9GpT+6789kbDUG2FUfJc0I7g3594aSwZIWu59W0BpLxeEaymF6do87676lqiI0UynCsNZnF+OlF0lYI+E9lb/yQdI62Wi/03SjYGx6svzvMxmWTtqBLGZoj1IAE7Mu09iu4eWp4qOopuXFdkH3RH1wQgyknKXZqC1xvhExguuQel+nyHwPi8e4AeqGrIaNhZ19KWauN82GQ9IimgsFmk96HPzDbN7ifzybcJ7iSMPiyZqLnK19g/WlSSjuR2l28j6Mt2zvJ5yeqV9B5GejZreLIG5sIJt5sEj4parKyshBsfn9pmZMhgaAJeYu1JRuA4VIHxFL1Ue8a8NhD50rtGs/5MDJl9LOTnqSnTKM6uUel5JNMelZ7Mthhjokyd8bxaebmv9csLU0ronRtQkHoJbBGWC5KBkek28adYzuJONMkhVA=
  on:
    branch: main
    repo: PaNOSC-ViNYL/SimEx-Lite
    python: 3.8
