language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: ZYHRDrJHTAp45GskHDjoGqLrjiDZnc2YcQNRxRMCyIa6EwSc5VP///Tg54bta9/ratyJ5db0WxdcN4FpUUN94wT025cuNlcfb9Pl8ojlgOY8uKqlujo/OfBylgBXXa65W0Ztzi/ASeDkWMiBL7bxCMMXVdc91nPrYbTOlDiFlHRa99sdhvOi3jrPxq3f3dOg5sk5Tyfp2leVtO9N9zKoJ3q1unKVUNEO6GHEzAua7C4/S0RRZ2IRA7pukRr2FdbSkcSVQ5luC32Oe7x6dOb+W+Wrw+QYRlcI5ErAf+Blm2Y9/vZzf5rw8Of8PVVqNRECGaf5m/znZAm3NK0sayE9zVS6qUPSLQdb39NZgQoQMWd1EI6edPJ8g+Fm4gfNHDkNqg1UGlKcBN3uqlqr8P2CZEe98NKX9XRM1oDcSXe2+mr7W6qQZz1LRVtF/h6lV8IRRNFPGZ2L/ADSJygVD9JT/0HT003OKSZ4sHoxWabyE/IMV+deHFk6P4R9w+19WX9/uEUbenZD4t/OAnp/4lXSs2BsFF6Tff3V9YT/pZGxtzVSm89bTOaQfnHjaunMVUmZjpjFJC8/9bGCj7WYKKEmPeV5noaEzfbvCun9d6tdTiP1TATdvNdeWGQ+nilduZreq4EIf0FEm72hHkEb6Rz2iNfkYs2x+/AptHJISZZHd+0=
  on:
    tags: true
    repo: PaNOSC-ViNYL/SimEx-Lite
    python: 3.8
