language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: JunCEEE
  password:
    secure: HsT0XHvR3uw7C7QssiYiIzJBNWER1hIFazrB2Ld8UejxlJxCMR6gdBdrt9fT0yBSi+BBYNiet9V9p/pPsoUoaPcFKABQzwlVZiAWrcjKB622lVL2n8pazMOCBqMrxQm8VVvU2dNI7flmiZDvSjJsXURDKPPEvSWLDGinaVJDmfwZC5GyXE7leXZTvIHG76R1jKvzM0joM7S1b6/eFnE/V6spFYv1Vlc1hfxyu7a5guWdf/+KfyeftGl7oQzzQp4bsJcL9O0QonOrpiWUaTEfdr4TOe3pvFwbAS3Zx1Vs7incvoN5pV/R915L6NG0GQmmrcziHWvfBHBvr872eNBcWKdOm9XWtx7aOGjUGJYWJffNb8xd6trIPrltUla3iwW1Dqc4oK5vUh/+lxX6+XfNSROKzeml/ebQZMOGFaMoaUBL85VGL+9NO+T9aRu17BWiesUruzHRnWDxZLg02nkS7zvMcvICNmq4YLXM5v45aw2uINCzEY0lUABBBpJhwzGNjliY5PEAN6kV3JRQLZXNef3hBXoRjH8fzEVbvwJK9l7V70c+1PqhVnD8RmNkW1Z+Qmlx2jSGte8mZb4vVPayT9ZDlrvD1O4o/pNO8468GS5LOc3y1VY5bJJT6tKCdhP9LkqQKmG47sbYgBcx1Qtd9Kfu6JmG/ZndnnYs6F83sfU=
  on:
    branch: main
    repo: PaNOSC-ViNYL/SimEx-Lite
    python: 3.8
