language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: JunCEEE
  password:
    secure: 3tDbpWiRMji9m7vFryqmxH060F3eu5kt5PX8PRnCFLwS5aKH9iRP2GvsPvEuCE+/SvQy47ITrBp7auwHVVXR+M2MgIR+xedN17RaQaecQsiuEoLMowoLHS4exr6qPKKKucUziglgq52ILl5B6zAtxIxzMAdBnFDL8IqpPJs38X+DJW0WWAZpmOF4h8YxnGzwVZMJf36r/fBUXDCagVCiAEPP0DxenNedOvZewUKLKdUlic5NKlmE5PtMuTVOcZ9CxepqKKQ1xUDOwR3ldCYU8uGXYfEQxxFS8Q+iTOhxqFHCcHowlesWPpUjZjuNtW1b/LSRCAYw9e7ubwkS5yONzmIhoo5sSnYuouRrL+eyYUjYzsWhuYBBSi8IevQ4GkHtc3DZLa1zDujcqFfCD9CfBFOYheJelXQBu6SbJtsjgSvKVZ9h7nbh+2XTWn19CEcu5kUCgIiFFsq8VfEAADlmeotNLJ4L5tuNQP0kTxcAm7S4Ljh8kkaZHXHP181qaeq+bPBKsrt+gs+WHjEgjlHnDgsODYVxo/C+cpB9bFh4jutvxU6HWW8bI6/Qxfg4nPViYXquAxWhesQP4WSpKBXyvcb2vWlOCBU9ymjvTWeuYA6nBgvedzZF2w0m8nxZXB00ewqh4MbBcNS2KvAxSrl53vXqX7IAhwJGO+QzvzZsndY=
  on:
    # tags: false
    branch: main
    repo: PaNOSC-ViNYL/SimEx-Lite
    python: 3.8
