language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password: pypi-AgEIcHlwaS5vcmcCJDU4YTg1ZGJlLTY3MTYtNGQwMy04YjYwLWQxZDQ1MDIyZTM2ZgACO3sicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJzaW1leC1saXRlIl19LCAidmVyc2lvbiI6IDF9AAAGIE-edvL8h2iwW646cyyQW9a-WE5U7v1z2addhDGLPn7x
  on:
    tags: true
    repo: PaNOSC-ViNYL/SimEx-Lite
    python: 3.8
