language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password: pypi-AgEIcHlwaS5vcmcCJGIxNGE4ZjkxLTg2ZjMtNDFkZC04Njk1LWFmNzk2ZTE5NmM4OAACO3sicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJzaW1leC1saXRlIl19LCAidmVyc2lvbiI6IDF9AAAGIBg-Y8aHSez6cY7I3x8tavHeiRBlSgwqTGwGbqsE2twy
  on:
    tags: true
    repo: PaNOSC-ViNYL/SimEx-Lite
    python: 3.8
